### ISSUE TITLE
How should streamify handle undefined in JSON?

### ISSUE THREAD

**Issue by GlynnPhillips** [fent/node-streamify#4]
I have noticed when streamify is passed a `json` object where some values are `undefined` it produces invalid `json`. The `undefined` values are striped out producing `json` like the following.

``` {"a": 1, "b":"c": 3} ```

Is this something which would be easily fixed or is this a behaviour you would expect?

Thanks

**Comment by fent** [comment]
By passed do you mean written to? It writes directly to the stream it's given, without modifying the object.

**Comment by GlynnPhillips** [comment]
Sorry this was me getting mixed up. I was using the bfj package and when I saw it using streamify I assumed it was this package but it turns out its not. 

This can be closed sorry for the mix up.
